apiVersion: core.contrail.juniper.net/v1alpha1
kind: Subnet
metadata:
  name: subnet1-v4
  namespace: ns1
  annotations:
    core.juniper.net/display-name: subnet1-v4
spec:
  cidr: 10.0.0.0/24
  defaultGateway: 10.0.0.1
---
apiVersion: core.contrail.juniper.net/v1alpha1
kind: VirtualNetwork
metadata:
  namespace: ns1
  name: vn1
spec:
  v4SubnetReference:
    apiVersion: core.contrail.juniper.net/v1alpha1
    kind: Subnet
    namespace: ns1
    name: subnet1-v4
---
apiVersion: core.contrail.juniper.net/v1alpha1
kind: Subnet
metadata:
  name: subnet2-v4
  namespace: ns1
  annotations:
    core.juniper.net/display-name: subnet2-v4
spec:
  cidr: 20.0.0.0/24
  defaultGateway: 20.0.0.1
---
apiVersion: core.contrail.juniper.net/v1alpha1
kind: VirtualNetwork
metadata:
  namespace: ns1
  name: vn2
spec:
  v4SubnetReference:
    apiVersion: core.contrail.juniper.net/v1alpha1
    kind: Subnet
    namespace: ns1
    name: subnet2-v4
---
apiVersion: core.contrail.juniper.net/v1alpha1
kind: Subnet
metadata:
  name: subnet3-v4
  namespace: ns1
  annotations:
    core.juniper.net/display-name: subnet3-v4
spec:
  cidr: 30.0.0.0/24
  defaultGateway: 30.0.0.1
---
apiVersion: core.contrail.juniper.net/v1alpha1
kind: VirtualNetwork
metadata:
  namespace: ns1
  name: vn3
spec:
  v4SubnetReference:
    apiVersion: core.contrail.juniper.net/v1alpha1
    kind: Subnet
    namespace: ns1
    name: subnet3-v4
---
apiVersion: v1
kind: Pod
metadata:
  name: centos1
  namespace: ns1
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [
        {
          "name": "vn1",
          "namespace": "ns1",
          "cni-args": {
              "net.juniper.contrail.interfacegroup": "eth1"
          }
        },
        {
          "name": "vn2",
          "namespace": "ns1",
          "cni-args": {
              "net.juniper.contrail.vlan": "100",
              "net.juniper.contrail.interfacegroup": "eth1"
          }
        },
        {
          "name": "vn3",
          "namespace": "ns1",
          "cni-args": {
              "net.juniper.contrail.vlan": "200",
              "net.juniper.contrail.interfacegroup": "eth1"
          }
        }
      ]
spec:
  containers:
  - name: centos1
    image: docker.io/centos
    command: [ "/bin/bash", "-c" ]
    args:
     - sleep infinity;
    securityContext:
      privileged: true
      capabilities:
        add:
          - NET_ADMIN

